### ISSUE TITLE
Let users modify the rounding behavior

### ISSUE THREAD

**Issue by hispanasian** [AronDavis/Time-Tracker#10]
1. Allow users to set the rounding interval in minutes (ie round to the next 15 minutes)
2. Allow the users to choose to round up (ceiling), down (floor), or in the middle (up after the middle or down before the middle)

**Comment by AronDavis** [comment]
When you're ready just update TimeUtility.cs

I can handle saving settings and all that.

**Comment by AronDavis** [comment]
Partially completed.
