### ISSUE TITLE
Time Edit UX Issue

### ISSUE THREAD

**Issue by hispanasian** [AronDavis/Time-Tracker#13]
When you edit the time for one of the issues, the timer stops. However, the button still says "Stop Timer" as if it was still going and you have to click the button twice to get back into a state where the timer starts up again (seems like the first click actually sets it into "stop timer" mode and the second puts it back into "start timer" mode). 

It should automatically be put into "stop timer" mode when you edit a time.

**Comment by AronDavis** [comment]
Fixed with latest change to #6.
